version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - multiplike_net
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=mysql+pymysql://root:multiplike@db:3306/multiplike_db
    restart: always
    depends_on:
      db:
        condition: service_healthy
  db:
    image: "mysql:8.1"
    networks:
      - multiplike_net
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=multiplike
      - MYSQL_DATABASE=multiplike_db
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3306"]
      interval: 5s
      start_period: 10s

networks:
  multiplike_net:
